name: brilliant_game
description: Motor de Brilliant con tableros, zonas y tipos de color para Flutter.

environment:
  sdk: '^3.9.0'

dependencies:
  bloc: ^9.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/characters/
    - assets/images/branding/
    - assets/images/ui/
    - assets/images/effects/

dev_dependencies:
  flutter_test:
    sdk: flutter
