name: brilliant_game
description: Motor de Brilliant con tableros, zonas y tipos de color para Flutter.

environment:
  sdk: '^3.9.0'

dependencies:
  bloc: ^9.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
